apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcBlockName }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: {{ .Values.volSize }}
  storageClassName: {{ .Values.scBlockName }}
