apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcNfsName }}-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.scNfsName }}
  resources:
    requests:
      storage: {{ .Values.volSize }}
  dataSource:
    kind: PersistentVolumeClaim
    name: {{ .Values.pvcSourceName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcNfsName }}-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.scNfsName }}
  resources:
    requests:
      storage: {{ .Values.volSize }}
  dataSource:
    kind: PersistentVolumeClaim
    name: {{ .Values.pvcSourceName }}