apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcNfsName }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volSize }}
  storageClassName: {{ .Values.scNfsName }}
