# Various names used through example
scBlockName: zfssa-block-example-sc
vscBlockName: zfssa-block-example-vsc
pvcBlockName: zfssa-block-example-pvc
podBlockName: zfssa-block-example-pod

# Location for images used
imageBase: container-registry.oracle.com/os/
images:
  os:
    name: oraclelinux
    tag: "7-slim"

# Settings for target appliance
appliance:
  volumeType: thin
  targetGroup: OVERRIDE
  pool: OVERRIDE
  project: OVERRIDE
  targetPortal: OVERRIDE
  nfsServer: OVERRIDE
  rootUser: root
  rootGroup: other

# Settings for volume
volSize: OVERRIDE
