apiVersion: v1
kind: Pod
metadata:
  name: zfssa-block-vs-restore-pod
  labels:
    name: ol7slim-test
spec:
  restartPolicy: Always
  containers:
    - image: {{ .Values.imageBase }}{{ .Values.images.os.name }}:{{ .Values.images.os.tag }}
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      name: ol7slim
      volumeDevices:
        - name: vol
          devicePath: /dev/block
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: zfssa-block-vs-restore-pvc
        readOnly: false
