apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.scBlockName }}
provisioner: zfssa-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  volumeType: {{ .Values.appliance.volumeType }}
  targetGroup: {{ .Values.appliance.targetGroup }}
  blockSize: "8192"
  pool: {{ .Values.appliance.pool }}
  project: {{ .Values.appliance.project }}
  targetPortal: {{ .Values.appliance.targetPortal }}
  nfsServer: {{ .Values.appliance.nfsServer }}
  rootUser: {{ .Values.appliance.rootUser }}
  rootGroup: {{ .Values.appliance.rootGroup }}
  rootPermissions: "777"
  shareNFS: {{ .Values.appliance.shareNFS }}
  restrictChown: "false"
