apiVersion: v1
stringData:
  zfssa.yaml: |
    username: {{ .Values.zfssaInformation.username }}
    password: {{ .Values.zfssaInformation.password }}
kind: Secret
metadata:
  name: oracle.zfssa.csi.node
  namespace: {{ .Values.deployment.namespace }}
