apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zfssa-block-vs-restore-pvc 
spec:
  storageClassName: zfssa-block-vs-example-sc
  dataSource:
    name: zfssa-block-vs-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 80Ki
